id: I42E7E51F
ocr_import_info:
  timestamp: '2023-06-28T07:18:14.258018+00:00'
  batch_id: batch-ad37
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 07:33:05.629236+00:00
last_modified: 2023-06-28 07:33:05.629245+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM835
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM835
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚིག་ལེའུར་བྱས་པ།
  languages:
  - bo
  author: ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.9621757030137069
  ocr_word_median_confidence_index: 0.9973411249999999
bases:
  I1NLM835_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM835_001
      total_pages: 172
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM835_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9973411249999999
      ocr_word_mean_confidence_index: 0.9621757030137069
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
